# Generated by Django 2.1.3 on 2018-12-14 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('published', models.BooleanField(default=True)),
                ('comment_allowed', models.BooleanField(default=True)),
                ('summary', models.TextField(help_text='Ringkasan - opsional', max_length=1000)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, help_text='Identitas pembuat artikel asli', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
