# Generated by Django 2.1.3 on 2018-12-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, help_text='Identitas pembuat artikel asli', max_length=100, null=True, verbose_name='Penulis:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_allowed',
            field=models.BooleanField(default=True, verbose_name='Izinkan komentar pembaca?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Isi artikel:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Rilis artikel?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Ringkasan (opsional):'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Judul:'),
        ),
    ]
